<?php
class Autor extends Controller
{
    public function __construct(){if(session_status()===PHP_SESSION_NONE)session_start();if(empty($_SESSION['activo'])){header('Location: '.base_url);exit;}parent::__construct();if(!$this->model->verificarPermisos($_SESSION['id_usuario'],'Autor')){$this->views->getView($this,'permisos');exit;}}
    public function index(){$this->views->getView($this,'index');}
    public function listar(){try{$data=$this->model->getAutor();foreach($data as &$r){$id=(int)$r['Idautor'];$activo=(int)$r['Autor_estado']===1;$r['Autor_estado']=$activo?'<span class="badge badge-success">Activo</span>':'<span class="badge badge-danger">Inactivo</span>';$r['acciones']=$activo?'<button class="btn btn-primary" onclick="btnEditarAutor('.$id.')"><i class="fa fa-pencil-square-o"></i></button> <button class="btn btn-danger" onclick="btnEliminarAutor('.$id.')"><i class="fa fa-trash-o"></i></button>':'<button class="btn btn-success" onclick="btnReingresarAutor('.$id.')"><i class="fa fa-reply-all"></i></button>';}$data=array_values($data);echo json_encode($data,JSON_UNESCAPED_UNICODE);exit;}catch(Throwable $e){error_log('Autor/listar '.$e->getMessage());http_response_code(500);echo json_encode(['error'=>'No fue posible cargar los autores'],JSON_UNESCAPED_UNICODE);exit;}}
    public function registrar(){$nombres=trim($_POST['Autor_nombres']??'');$apellidos=trim($_POST['Autor_apellidos']??'');$pais=trim($_POST['Autor_pais']??'');$id=(int)($_POST['Idautor']??0);if($nombres===''||$apellidos===''){echo json_encode(['msg'=>'Nombres y apellidos son requeridos','icono'=>'warning']);exit;}$d=$id===0?$this->model->insertarAutor($nombres,$apellidos,$pais):$this->model->actualizarAutor($nombres,$apellidos,$pais,$id);$m=['ok'=>['Autor registrado','success'],'existe'=>['El autor ya existe','warning'],'modificado'=>['Autor modificado','success']];$r=$m[$d]??['Error al guardar el autor','error'];echo json_encode(['msg'=>$r[0],'icono'=>$r[1]],JSON_UNESCAPED_UNICODE);exit;}
    public function editar($id){echo json_encode($this->model->editAutor((int)$id),JSON_UNESCAPED_UNICODE);exit;}
    public function eliminar($id){$ok=$this->model->estadoAutor(0,(int)$id);echo json_encode(['msg'=>$ok?'Autor dado de baja':'Error al eliminar','icono'=>$ok?'success':'error']);exit;}
    public function reingresar($id){$ok=$this->model->estadoAutor(1,(int)$id);echo json_encode(['msg'=>$ok?'Autor restaurado':'Error al restaurar','icono'=>$ok?'success':'error']);exit;}
    public function buscarAutor(){echo json_encode($this->model->buscarAutor(trim($_GET['q']??'')),JSON_UNESCAPED_UNICODE);exit;}
}
?>